spring:
  application:
    name: "Sistema de testes"
  datasource:
    url: jdbc:h2:mem:testdb
    console.path: /h2-console
    console.enabled: true
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true