spring:
  application:
    name: feign-test-retry

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
        loggerLevel: BASIC
        errorDecoder: com.upmasters.feignTestRetry.feignClients.errors.DrmClientErrorDecoder
        retryer: com.upmasters.feignTestRetry.config.FeignRetry
      example:
        errorDecoder: com.upmasters.feignTestRetry.feignClients.errors.ClientErrorDecoder